### ISSUE TITLE
At startup settings screen appears and stays on display until manually closed

### ISSUE THREAD

**Issue by Drucker03** [tanin47/noo#16]
Every time I start my Mac Noo's settings screen appears. It stays present until I close it. I see this behavior since the last update. System version is macOS 13.6.5

**Comment by tanin47** [comment]
@Drucker03 Thank you for reporting this.

The new version always opens the window when Noo is started, and Noo is started at the startup (I assume you set it to do so). This is because there are multiple complaints that users cannot find Noo after starting it.

Let me think about how to balance this better. There might be a way to avoid opening the window only at the startup, but still opens the window if started manually.

Thank you again for using Noo.

**Comment by Drucker03** [comment]
Thank you for your quick answer. On my Mac Noo resides in the menu bar - I never had any problems to find it. And if not it still would be in the applications folder. So I can't fully understand the userers you mentioned. 

Maybe it would be a good idea to let the user choose if the the window should be opened at startup or not. The settings could be the right place to do so.

**Comment by tanin47** [comment]
Thank you again. I totally understand the annoyance. I'll solve this in the next version.

**Comment by Drucker03** [comment]
Thank you, this is highly appreciated.

**Comment by tanin47** [comment]
This has been improved here: https://github.com/tanin47/noo/commit/0477c5d6c1f442dd703048d63e57a12f33eaff6f

The new version 3.2 has been published. You can head to the AppStore to update Noo: https://apps.apple.com/us/app/noo-mouse/id1514904040

I wonder if I can ask for 2 favors:

1. Can you test it by restarting your machine? to see whether the window still opens. It shouldn't.
2. I wonder if you can help write review on the app store. 

Thank you so much.

**Comment by Drucker03** [comment]
Thank you. I updated the app and it works like promised. After restarting the machin there is no settings screen visible while the app functions without problems and shows it's little icon in the menu bar.

I will review it on the app store.

**Comment by tanin47** [comment]
Thank you so much!
