### ISSUE TITLE
Noo not working on os 10.15 (for me)

### ISSUE THREAD

**Issue by Mikehc45** [tanin47/noo#8]
No idea what to do after installation.  Says it's running (because I can't bin it), but need next steps to be able to reprogram mouse buttons
Mike

**Comment by RogueTHH** [comment]
I get an icon on the top right of the screen left of all the others near the clock. When I program an appropriate button (the numbers here do not correspond to the Baibao 103 diagram) all I get is a click. I am running macOS Monterey 12.2.1.

**Comment by tanin47** [comment]
I apologize about the inconvenience. I initially wrote this app to use it myself with [Tip](https://github.com/tanin47/tip), so I didn't invest much in the user experience. 

I've improved the user experience around granting the Accessibility permission. The app didn't start because the Accessibility permission wasn't granted. Now the app will give you a proper warning if the Accessibility permission is not granted.

You can download the new version (released today) here: https://apps.apple.com/us/app/noo-mouse/id1514904040?mt=12
